export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    REMOVE_ALL: "REMOVE_ALL",
    SET_CART_LOCAL: "SET_CART_LOCAL",
    SUBS_TO_CART: "SUBS_TO_CART",
}